basePath: /api/v1
definitions:
  auth.Auth:
    properties:
      token:
        type: string
      token_type:
        type: string
    type: object
  auth.LoginRequest:
    properties:
      password:
        type: string
      user_name:
        type: string
    required:
    - password
    - user_name
    type: object
  auth.LoginResponse:
    properties:
      auth:
        $ref: '#/definitions/auth.Auth'
    type: object
  utils.Error:
    properties:
      errors:
        additionalProperties: true
        type: object
    type: object
info:
  contact: {}
  description: Professional API documentation for the Mini Shop backend
  title: Mini Shop API
  version: 1.0.0
paths:
  /front/auth:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a token
      parameters:
      - description: Credentials to use
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Error'
      summary: Login
      tags:
      - Admin/Auth
schemes:
- http
swagger: "2.0"
